# UTS-2 My Songs for You

Lagu “Monokrom” merupakan ungkapan terima kasih
kepada orang- orang yang sempat muncul serta berikan warna dalam hidup baik keluarga,
teman, orang terdekat, maupun masalalu yang telah membentuk diri kita.

Meski kata monokrom berarti “satu warna” (hitam- putih),
lagu ini justru menggambarkan bagaimana kenangan, walaupun bisa jadi tidak senantiasa indah,
tetap memiliki nilai serta keindahan tersendiri. 

{{< video https://www.youtube.com/watch?v=QqJ-Vp8mvbk>}}, with lyrics

[Lirik "Monokrom"]

[Verse 1]
Lembaran foto hitam putih
Aku coba ingat lagi warna bajumu kala itu
Kali pertama di hidupku
Manusia lain memelukku

[Verse 2]
Lembaran foto hitam putih
Aku coba ingat lagi wangi rumah di sore itu
Kue cokelat balon warna-warni
Pesta hari ulang tahunku

[Chorus]
Dimanapun kalian berada
Kukirimkan terima kasih
Untuk warna dalam hidupku dan banyak kenangan indah
Kau melukis aku

[Verse 3]
Lembaran foto hitam putih
Kembali teringat malam kuhitung-hitung bintang
Saat mataku sulit tidur
Suaramu buatku lelap
You might also like
[Chorus]
Dimanapun kalian berada
Kukirimkan terima kasih
Untuk warna dalam hidupku dan banyak kenangan indah
Kau melukis aku

[Bridge]
Kita tak pernah tahu berapa lama kita
Diberi waktu
Jika aku pergi lebih dulu jangan lupakan aku
Ini lagu untukmu
Ungkapan terima kasihku

[Outro]
Lembar monokrom hitam putih
Aku coba ingat warna demi warna di hidupku
Tak akan 'ku mengenal cinta
Bila bukan karena hati baikmu